use_multithreading = false      # 将其更改为 true 来启用多线程
wait_time = 5.0                 # 每次尝试后的等待时间（秒）
username = "your_username_here"
password = "your_password_here"
browser = "edge"                # 可以是 "chrome", "firefox", 或 "edge"

# 课程信息列表
[[courses]]
KCH = "08305014" # 课程号
JSH = "1005"     # 教师号


[[courses]]
KCH = "0830SY02"
JSH = "1001"
